language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=sqlite
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:create rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec

