---
development:
  cloud_name: generic-cloudinary
  api_key: '484828788832287'
  api_secret: u0GUEBFemDeP0OcmDvChnF8KevM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: generic-cloudinary
  api_key: '484828788832287'
  api_secret: u0GUEBFemDeP0OcmDvChnF8KevM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: generic-cloudinary
  api_key: '484828788832287'
  api_secret: u0GUEBFemDeP0OcmDvChnF8KevM
  enhance_image_tag: true
  static_image_support: false
